"""KG coverage audit — HDI-Safe-50 vs public HDI references.

Compares the in-scope HDI-Safe-50 panel against curated public HDI
references (NIH ODS herb factsheets + NCCIH herb-drug interaction
summaries).

Output: research-journal-relative HDI universe estimate + overlap %.

Per Paper 1 §E5: this audit informs the HDI Recall denominator
interpretation. If HDI-Safe-50 covers <20% of the universe, the metric
is testing in-scope recall, not absolute recall — paper Limitations
must say so.

Note: We do NOT scrape NIH ODS / NCCIH live (license-uncertain). Instead,
we maintain a curated HDI reference list at
  research-journal/shared/datasets/hdi-public-references.json
and compare HDI-Safe-50 against that.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parent.parent  # shrine-diet-bioactivity/
GIT_ROOT = REPO.parent
HDI_SAFE_50 = GIT_ROOT / "research-journal" / "shared" / "hdi_safe_50.json"
PUBLIC_REFS = GIT_ROOT / "research-journal" / "shared" / "datasets" / "hdi-public-references.json"
OUTPUT = GIT_ROOT / "docs" / "kg-coverage-audit.md"


def _normalize_pair(drug: str, herb: str) -> tuple[str, str]:
    return (drug.strip().lower(), herb.strip().lower())


def _entry_name(value) -> str:
    """Return a name string from either a flat string or a `{name, ...}` object."""
    if isinstance(value, str):
        return value
    if isinstance(value, dict):
        return str(value.get("name", "") or "")
    return ""


def _extract_pairs_from_entries(entries) -> set[tuple[str, str]]:
    """Extract (drug, herb) pairs from a list of HDI entries.

    Handles both shapes used across the project:
      - flat:   {"drug": "Warfarin", "herb": "Ginkgo biloba", ...}
      - nested: {"drug": {"name": "Sertraline", "atc": ...},
                 "herb": {"name": "St. John's Wort", "latin": ...}, ...}
    """
    pairs: set[tuple[str, str]] = set()
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        drug = _entry_name(entry.get("drug"))
        herb = _entry_name(entry.get("herb"))
        if drug and herb:
            pairs.add(_normalize_pair(drug, herb))
    return pairs


def _extract_pairs_from_safe(data) -> set[tuple[str, str]]:
    """Adapt to the actual HDI-Safe-50 schema.

    The live file is a top-level JSON list of nested-object entries, but
    we also accept dict-wrapped variants for forward compatibility.
    """
    if isinstance(data, list):
        return _extract_pairs_from_entries(data)
    if isinstance(data, dict):
        for key in ("interactions", "hdi", "entries", "data"):
            value = data.get(key)
            if isinstance(value, list):
                return _extract_pairs_from_entries(value)
    return set()


def main() -> int:
    if not HDI_SAFE_50.exists():
        print(f"ERROR: HDI-Safe-50 not found at {HDI_SAFE_50}", file=sys.stderr)
        return 1
    if not PUBLIC_REFS.exists():
        print(f"ERROR: public refs not found at {PUBLIC_REFS}", file=sys.stderr)
        print("Bootstrap with hdi-public-references.json before running.", file=sys.stderr)
        return 1

    safe_data = json.loads(HDI_SAFE_50.read_text())
    public_data = json.loads(PUBLIC_REFS.read_text())

    safe_pairs = _extract_pairs_from_safe(safe_data)
    public_pairs = _extract_pairs_from_entries(public_data.get("interactions", []))

    if not safe_pairs:
        print(f"ERROR: failed to extract any (drug, herb) pairs from {HDI_SAFE_50}", file=sys.stderr)
        return 2

    overlap = safe_pairs & public_pairs
    safe_only = safe_pairs - public_pairs
    public_only = public_pairs - safe_pairs
    universe = safe_pairs | public_pairs

    coverage_pct = (len(safe_pairs) / len(universe) * 100) if universe else 0.0
    overlap_pct = (len(overlap) / len(public_pairs) * 100) if public_pairs else 0.0

    md = [
        "# HDI-Safe-50 Coverage Audit",
        "",
        "_Generated by `scripts/kg_coverage_audit.py`. Companion to Paper 1 §E5._",
        "",
        f"- HDI-Safe-50 entries: **{len(safe_pairs)}**",
        f"- Curated public references: **{len(public_pairs)}**",
        f"- Union (estimated HDI universe within tracked scope): **{len(universe)}**",
        f"- Overlap (in both): **{len(overlap)}**",
        f"- HDI-Safe-50 coverage of universe: **{coverage_pct:.1f}%**",
        f"- HDI-Safe-50 coverage of public-references subset: **{overlap_pct:.1f}%**",
        "",
        "## Implications for Paper 1 HDI Recall metric",
        "",
        f"HDI Recall measures how often the panel surfaces gold HDI claims for "
        f"scenarios drawn from the HDI-Safe-50 panel. The metric's denominator "
        f"is in-panel — it does NOT measure recall against the broader HDI "
        f"universe.",
        "",
        f"At {coverage_pct:.1f}% coverage of the curated public-reference universe, "
        f"this is an **in-scope HDI recall** metric. The paper Limitations "
        f"section must say so explicitly: \"HDI Recall is computed against the "
        f"HDI-Safe-50 reference panel, which covers approximately "
        f"{coverage_pct:.0f}% of the curated public HDI universe known to NIH "
        f"ODS and NCCIH (per `docs/kg-coverage-audit.md`).\"",
        "",
        "## Update procedure",
        "",
        "1. Pull recent NIH ODS herb factsheets and NCCIH herb-drug summaries.",
        "2. Append new (drug, herb, severity, source) entries to "
        "`research-journal/shared/datasets/hdi-public-references.json`.",
        "3. Re-run `python3 -m scripts.kg_coverage_audit` to refresh this doc.",
        "",
    ]

    if safe_only:
        md.extend([
            "## Pairs in HDI-Safe-50 but not in public references",
            "(Either we know more than the public sources, or the public list "
            "needs an update.)",
            "",
            *(f"- {d} × {h}" for d, h in sorted(safe_only)),
            "",
        ])
    if public_only:
        md.extend([
            "## Pairs in public references but not in HDI-Safe-50",
            "(Candidate additions to v2 panel expansion.)",
            "",
            *(f"- {d} × {h}" for d, h in sorted(public_only)),
            "",
        ])

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(md))
    print(f"wrote {OUTPUT}")
    print(f"  HDI-Safe-50: {len(safe_pairs)}, public refs: {len(public_pairs)}, universe: {len(universe)}, coverage: {coverage_pct:.1f}%")
    return 0


if __name__ == "__main__":
    sys.exit(main())
